services:
  - type: web
    name: ogsl-project
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ogsl_core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false
    postDeployCommand: |
      echo "🚀 Running migrations on Render Free Plan..."
      python manage.py makemigrations --noinput
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
      echo "✅ Migrations completed successfully!"
