services:
  - type: web
    name: ogsl-project
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ogsl_core.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false
